version: "3.9"
services:
  redis:
    image: redis
    container_name: redis
    environment:
      - REDIS_PASSWORD=EXAMPLE_PASS
    volumes:
      - D:/docker/redis:/data
    command: redis-server --save 20 1 --requirepass EXAMPLE_PASS
  pasty:
    image: pasty
    container_name: pasty
    depends_on:
      - redis
    environment:
      - STORAGE=REDIS
      - REDIS_CONNECTION=redis://EXAMPLE_PASS@redis:6379
      - KEYGEN=PHONETIC
      - LANGS=MIN
    volumes:
      - D:/docker/pasty:/data
    ports:
      - "8080:8080"
