version: "3.9"
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=EXAMPLE_ACCESS
      - MINIO_ROOT_PASSWORD=EXAMPLE_SECRET
    volumes:
      - D:/docker/minio:/data
    command: server /data
  bucket:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 EXAMPLE_ACCESS EXAMPLE_SECRET;
      /usr/bin/mc mb minio/pasty;
      exit 0;
      "
  pasty:
    image: pasty
    container_name: pasty
    depends_on:
      - bucket
    environment:
      - STORAGE=S3
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=pasty
      - S3_REGION=auto
      - S3_ACCESS=EXAMPLE_ACCESS
      - S3_SECRET=EXAMPLE_SECRET
      - KEYGEN=PHONETIC
      - LANGS=MIN
    volumes:
      - D:/docker/pasty:/data
    ports:
      - "8080:8080"
